Fix TypeError from backend_qt4.py
with `%matplotlib qt`, the line `plt.imshow(image)` generates a long TypeError traceback, ending in backend_qt4.py, with "TypeError: __init__() missing 1 required positional argument: 'figure'"

Accordingly, as a workaround, change `%matplotlib qt` to `%matplotlib inline`.